/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISalaryManagement,
  ISalaryManagementInterface,
} from "../../interfaces/ISalaryManagement";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_teacher",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
    ],
    name: "paySalary",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_teacher",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_salary",
        type: "uint256",
      },
      {
        internalType: "enum ISalaryManagement.Status",
        name: "_status",
        type: "uint8",
      },
    ],
    name: "registerTeacher",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_teacher",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "index",
        type: "uint256",
      },
      {
        internalType: "enum ISalaryManagement.Status",
        name: "_status",
        type: "uint8",
      },
    ],
    name: "updateTeacherStatus",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ISalaryManagement__factory {
  static readonly abi = _abi;
  static createInterface(): ISalaryManagementInterface {
    return new Interface(_abi) as ISalaryManagementInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISalaryManagement {
    return new Contract(address, _abi, runner) as unknown as ISalaryManagement;
  }
}
