/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockUniswapRouterSol from "./MockUniswapRouter.sol";
export type { mockUniswapRouterSol };
import type * as permitSwapSol from "./PermitSwap.sol";
export type { permitSwapSol };
export type { Lock } from "./Lock";
export type { MockToken } from "./MockToken";
