/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IPiggyBank {
  export type SavingsPlanStruct = {
    balance: BigNumberish;
    lockPeriod: BigNumberish;
    startTime: BigNumberish;
    isEther: boolean;
    token: AddressLike;
  };

  export type SavingsPlanStructOutput = [
    balance: bigint,
    lockPeriod: bigint,
    startTime: bigint,
    isEther: boolean,
    token: string
  ] & {
    balance: bigint;
    lockPeriod: bigint;
    startTime: bigint;
    isEther: boolean;
    token: string;
  };
}

export interface IPiggyBankInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositEther"
      | "depositToken"
      | "getBalance"
      | "getSavingsPlan"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Deposited" | "SavingsPlanCreated" | "Withdrawn"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "depositEther",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSavingsPlan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSavingsPlan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace DepositedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    isEther: boolean,
    token: AddressLike,
    lockPeriod: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    isEther: boolean,
    token: string,
    lockPeriod: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    isEther: boolean;
    token: string;
    lockPeriod: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SavingsPlanCreatedEvent {
  export type InputTuple = [
    planId: BigNumberish,
    lockPeriod: BigNumberish,
    isEther: boolean,
    token: AddressLike
  ];
  export type OutputTuple = [
    planId: bigint,
    lockPeriod: bigint,
    isEther: boolean,
    token: string
  ];
  export interface OutputObject {
    planId: bigint;
    lockPeriod: bigint;
    isEther: boolean;
    token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawnEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    isEther: boolean,
    token: AddressLike,
    penalty: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    isEther: boolean,
    token: string,
    penalty: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    isEther: boolean;
    token: string;
    penalty: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPiggyBank extends BaseContract {
  connect(runner?: ContractRunner | null): IPiggyBank;
  waitForDeployment(): Promise<this>;

  interface: IPiggyBankInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositEther: TypedContractMethod<
    [lockPeriod: BigNumberish],
    [void],
    "payable"
  >;

  depositToken: TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, lockPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<[planId: BigNumberish], [bigint], "view">;

  getSavingsPlan: TypedContractMethod<
    [planId: BigNumberish],
    [IPiggyBank.SavingsPlanStructOutput],
    "view"
  >;

  withdraw: TypedContractMethod<[planId: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositEther"
  ): TypedContractMethod<[lockPeriod: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "depositToken"
  ): TypedContractMethod<
    [token: AddressLike, amount: BigNumberish, lockPeriod: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[planId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSavingsPlan"
  ): TypedContractMethod<
    [planId: BigNumberish],
    [IPiggyBank.SavingsPlanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[planId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "Deposited"
  ): TypedContractEvent<
    DepositedEvent.InputTuple,
    DepositedEvent.OutputTuple,
    DepositedEvent.OutputObject
  >;
  getEvent(
    key: "SavingsPlanCreated"
  ): TypedContractEvent<
    SavingsPlanCreatedEvent.InputTuple,
    SavingsPlanCreatedEvent.OutputTuple,
    SavingsPlanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Withdrawn"
  ): TypedContractEvent<
    WithdrawnEvent.InputTuple,
    WithdrawnEvent.OutputTuple,
    WithdrawnEvent.OutputObject
  >;

  filters: {
    "Deposited(address,uint256,bool,address,uint256)": TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;
    Deposited: TypedContractEvent<
      DepositedEvent.InputTuple,
      DepositedEvent.OutputTuple,
      DepositedEvent.OutputObject
    >;

    "SavingsPlanCreated(uint256,uint256,bool,address)": TypedContractEvent<
      SavingsPlanCreatedEvent.InputTuple,
      SavingsPlanCreatedEvent.OutputTuple,
      SavingsPlanCreatedEvent.OutputObject
    >;
    SavingsPlanCreated: TypedContractEvent<
      SavingsPlanCreatedEvent.InputTuple,
      SavingsPlanCreatedEvent.OutputTuple,
      SavingsPlanCreatedEvent.OutputObject
    >;

    "Withdrawn(address,uint256,bool,address,uint256)": TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
    Withdrawn: TypedContractEvent<
      WithdrawnEvent.InputTuple,
      WithdrawnEvent.OutputTuple,
      WithdrawnEvent.OutputObject
    >;
  };
}
