/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as companyInterfaceSol from "./CompanyInterface.sol";
export * as companyFactorySol from "./companyFactory.sol";
export { Company__factory } from "./Company__factory";
export { Error__factory } from "./Error__factory";
export { Ether__factory } from "./Ether__factory";
