/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SmsMapping } from "./SmsMapping";
export * as factories from "./factories";
export { SmsMapping__factory } from "./factories/SmsMapping__factory";
