/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Schoolmanagement } from "./Schoolmanagement";
export * as factories from "./factories";
export { Schoolmanagement__factory } from "./factories/Schoolmanagement__factory";
