/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISchoolManagementSystem__factory } from "./ISchoolManagementSystem__factory";
export { SchoolManagementSystem__factory } from "./SchoolManagementSystem__factory";
