
[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
lisk_testnet= "https://rpc.sepolia-api.lisk.com"

[etherscan]
sepolia = { key = "123" }



# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
