/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ISchoolManagementSystem {
  export type EmployeeDetailsStruct = {
    name: string;
    role: BigNumberish;
    salary: BigNumberish;
    isEmployed: boolean;
  };

  export type EmployeeDetailsStructOutput = [
    name: string,
    role: bigint,
    salary: bigint,
    isEmployed: boolean
  ] & { name: string; role: bigint; salary: bigint; isEmployed: boolean };
}

export interface ISchoolManagementSystemInterface extends Interface {
  getFunction(
    nameOrSignature: "get_all_employees" | "pay_salary" | "register_employee"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "get_all_employees",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pay_salary",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "register_employee",
    values: [AddressLike, string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "get_all_employees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pay_salary", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "register_employee",
    data: BytesLike
  ): Result;
}

export interface ISchoolManagementSystem extends BaseContract {
  connect(runner?: ContractRunner | null): ISchoolManagementSystem;
  waitForDeployment(): Promise<this>;

  interface: ISchoolManagementSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  get_all_employees: TypedContractMethod<
    [],
    [ISchoolManagementSystem.EmployeeDetailsStructOutput[]],
    "view"
  >;

  pay_salary: TypedContractMethod<[_employee: AddressLike], [void], "payable">;

  register_employee: TypedContractMethod<
    [
      _employee: AddressLike,
      _name: string,
      _role: BigNumberish,
      _salary: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "get_all_employees"
  ): TypedContractMethod<
    [],
    [ISchoolManagementSystem.EmployeeDetailsStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "pay_salary"
  ): TypedContractMethod<[_employee: AddressLike], [void], "payable">;
  getFunction(
    nameOrSignature: "register_employee"
  ): TypedContractMethod<
    [
      _employee: AddressLike,
      _name: string,
      _role: BigNumberish,
      _salary: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
