/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EmployeeManagement } from "./EmployeeManagement";
export type { IEmployeeManagement } from "./IEmployeeManagement";
export * as factories from "./factories";
export { EmployeeManagement__factory } from "./factories/EmployeeManagement__factory";
export { IEmployeeManagement__factory } from "./factories/IEmployeeManagement__factory";
