/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
import type * as errors from "./errors";
export type { errors };
import type * as interfaces from "./interfaces";
export type { interfaces };
export * as factories from "./factories";
export type { Child } from "./contracts/Child";
export { Child__factory } from "./factories/contracts/Child__factory";
export type { StaffManagement } from "./contracts/StaffManagement";
export { StaffManagement__factory } from "./factories/contracts/StaffManagement__factory";
export type { Error } from "./errors/Error";
export { Error__factory } from "./factories/errors/Error__factory";
export type { ISalaryManagement } from "./interfaces/ISalaryManagement";
export { ISalaryManagement__factory } from "./factories/interfaces/ISalaryManagement__factory";
