/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type { MINT, MINTInterface } from "../../../contracts/DAONFT.sol/MINT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_to",
        type: "address",
      },
      {
        internalType: "string",
        name: "_tokenURI",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class MINT__factory {
  static readonly abi = _abi;
  static createInterface(): MINTInterface {
    return new Interface(_abi) as MINTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MINT {
    return new Contract(address, _abi, runner) as unknown as MINT;
  }
}
