/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoSol from "./DAO.sol";
export type { daoSol };
export type { MembershipNFT } from "./MembershipNFT";
export type { RolesRegistry7432 } from "./RolesRegistry7432";
export type { TokenGatedDAO } from "./TokenGatedDAO";
