[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
viaIR = true


remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@uniswap/v2-periphery/=lib/v2-periphery/",
  "@uniswap/v3-periphery/=lib/v3-periphery/",
  "@uniswap/v3-core/=lib/v3-core/",
  "forge-std/=lib/forge-std/src/"
]


[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
