[profile.default]
     src = "src"
     out = "out"
     libs = ["lib"]
     solc_version = "0.8.20"
     remappings = [
         "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
         "forge-std/=lib/forge-std/src/"
     ]

     [rpc_endpoints]
     lisk_sepolia = "${LISK_SEPOLIA_RPC_URL}"

     [etherscan]
     lisk_sepolia = { key = "123", chain = 4202, url = "https://sepolia-blockscout.lisk.com/api" }