[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "@uniswap/v3-periphery/contracts/=lib/v3-periphery/contracts/",
  "permit2/=lib/permit2/src/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@uniswap/v3-core/=lib/v3-core/",
  "@uniswap/permit2/=lib/permit2/",
  "@uniswap/universal-router/=lib/universal-router/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
