
     [profile.default]
     src = "src"
     out = "out"
     libs = ["lib"]
     solc_version = "0.8.20"
     optimizer = true
     optimizer_runs = 200
     remappings = [
       "forge-std/=lib/forge-std/src/",
       "@openzeppelin/=lib/openzeppelin-contracts/",
        "@chainlink/contracts/=lib/chainlink/contracts/"

     ]

     [profile.default.rpc_endpoints]
     sepolia = "https://sepolia.infura.io/v3/${39b278eb0e0447e7a20c87dd0a89cbb2}"

     [etherscan]
      sepolia = { key = "${1T1A5GBSRZZQ7KS346VYCSJ7MVBXWAMFQA}" }
     
     [profile.default.wallet]
      key = "default"  # Use the keystore named "default"

