/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { CustomNFT__factory } from "./CustomNFT__factory";
export { IERC721Receiver__factory } from "./IERC721Receiver__factory";
