/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CreateNewTodoList"
      | "getAllTodoLists"
      | "getTodoListCount"
      | "listOfTodoContracts"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "CreateNewTodoList",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllTodoLists",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTodoListCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listOfTodoContracts",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "CreateNewTodoList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllTodoLists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTodoListCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listOfTodoContracts",
    data: BytesLike
  ): Result;
}

export interface Factory extends BaseContract {
  connect(runner?: ContractRunner | null): Factory;
  waitForDeployment(): Promise<this>;

  interface: FactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CreateNewTodoList: TypedContractMethod<[], [void], "nonpayable">;

  getAllTodoLists: TypedContractMethod<[], [string[]], "view">;

  getTodoListCount: TypedContractMethod<[], [bigint], "view">;

  listOfTodoContracts: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CreateNewTodoList"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllTodoLists"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTodoListCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listOfTodoContracts"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  filters: {};
}
