/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TodoList {
  export type TodoStruct = {
    title: string;
    description: string;
    status: boolean;
    owner: AddressLike;
  };

  export type TodoStructOutput = [
    title: string,
    description: string,
    status: boolean,
    owner: string
  ] & { title: string; description: string; status: boolean; owner: string };
}

export interface TodoListInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "create_todo_for_sender"
      | "delete_todo"
      | "get_todos"
      | "get_todos_by_address"
      | "todos"
      | "todosByAddress"
      | "toggle_todo_status"
      | "update_todo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "create_todo_for_sender",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "delete_todo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "get_todos", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "get_todos_by_address",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "todos", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "todosByAddress",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "toggle_todo_status",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "update_todo",
    values: [BigNumberish, string, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "create_todo_for_sender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "delete_todo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "get_todos", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "get_todos_by_address",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "todos", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "todosByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "toggle_todo_status",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "update_todo",
    data: BytesLike
  ): Result;
}

export interface TodoList extends BaseContract {
  connect(runner?: ContractRunner | null): TodoList;
  waitForDeployment(): Promise<this>;

  interface: TodoListInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  create_todo_for_sender: TypedContractMethod<
    [_title: string, _description: string],
    [void],
    "nonpayable"
  >;

  delete_todo: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  get_todos: TypedContractMethod<[], [TodoList.TodoStructOutput[]], "view">;

  get_todos_by_address: TypedContractMethod<
    [_userAddress: AddressLike],
    [TodoList.TodoStructOutput[]],
    "view"
  >;

  todos: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, string] & {
        title: string;
        description: string;
        status: boolean;
        owner: string;
      }
    ],
    "view"
  >;

  todosByAddress: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, boolean, string] & {
        title: string;
        description: string;
        status: boolean;
        owner: string;
      }
    ],
    "view"
  >;

  toggle_todo_status: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  update_todo: TypedContractMethod<
    [_index: BigNumberish, _new_title: string, _new_description: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "create_todo_for_sender"
  ): TypedContractMethod<
    [_title: string, _description: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delete_todo"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "get_todos"
  ): TypedContractMethod<[], [TodoList.TodoStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "get_todos_by_address"
  ): TypedContractMethod<
    [_userAddress: AddressLike],
    [TodoList.TodoStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "todos"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, boolean, string] & {
        title: string;
        description: string;
        status: boolean;
        owner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "todosByAddress"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, string, boolean, string] & {
        title: string;
        description: string;
        status: boolean;
        owner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "toggle_todo_status"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "update_todo"
  ): TypedContractMethod<
    [_index: BigNumberish, _new_title: string, _new_description: string],
    [void],
    "nonpayable"
  >;

  filters: {};
}
