[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false

[rpc_endpoints]
lisk-sepolia = "https://rpc.sepolia.lisk.com"
eth-sepolia = "https://rpc.sepolia.org"
celo-alfajores = "https://alfajores-forno.celo-testnet.org"

[etherscan]
lisk-sepolia = { key = "", url = "https://rpc.sepolia.lisk.com" }
eth-sepolia = { key = "", url = "https://rpc.sepolia.org" }
celo-alfajores = { key = "", url = "https://alfajores-forno.celo-testnet.org" }
