/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace SchoolManagementSystem {
  export type StudentStruct = {
    name: string;
    age: BigNumberish;
    email: string;
    gender: BigNumberish;
    status: BigNumberish;
    school_name: string;
  };

  export type StudentStructOutput = [
    name: string,
    age: bigint,
    email: string,
    gender: bigint,
    status: bigint,
    school_name: string
  ] & {
    name: string;
    age: bigint;
    email: string;
    gender: bigint;
    status: bigint;
    school_name: string;
  };
}

export interface SchoolManagementSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ChangeStatus"
      | "DeleteStudent"
      | "RegisterStudent"
      | "UpdateStudent"
      | "ViewStudent"
      | "ViewStudents"
      | "studentAddresses"
      | "students"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "ChangeStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "DeleteStudent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "RegisterStudent",
    values: [string, BigNumberish, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "UpdateStudent",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ViewStudent",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ViewStudents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "studentAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "students",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "ChangeStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "DeleteStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "RegisterStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UpdateStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ViewStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ViewStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "studentAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "students", data: BytesLike): Result;
}

export interface SchoolManagementSystem extends BaseContract {
  connect(runner?: ContractRunner | null): SchoolManagementSystem;
  waitForDeployment(): Promise<this>;

  interface: SchoolManagementSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ChangeStatus: TypedContractMethod<
    [_new_status: BigNumberish],
    [void],
    "nonpayable"
  >;

  DeleteStudent: TypedContractMethod<[], [void], "nonpayable">;

  RegisterStudent: TypedContractMethod<
    [
      _name: string,
      _age: BigNumberish,
      _email: string,
      _gender: BigNumberish,
      _status: BigNumberish,
      _school_name: string
    ],
    [void],
    "nonpayable"
  >;

  UpdateStudent: TypedContractMethod<
    [_new_name: string, _new_age: BigNumberish],
    [void],
    "nonpayable"
  >;

  ViewStudent: TypedContractMethod<
    [],
    [
      [string, bigint, string, bigint, bigint] & {
        name: string;
        age: bigint;
        email: string;
        gender: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  ViewStudents: TypedContractMethod<
    [],
    [SchoolManagementSystem.StudentStructOutput[]],
    "view"
  >;

  studentAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  students: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, bigint, bigint, string] & {
        name: string;
        age: bigint;
        email: string;
        gender: bigint;
        status: bigint;
        school_name: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ChangeStatus"
  ): TypedContractMethod<[_new_status: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "DeleteStudent"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "RegisterStudent"
  ): TypedContractMethod<
    [
      _name: string,
      _age: BigNumberish,
      _email: string,
      _gender: BigNumberish,
      _status: BigNumberish,
      _school_name: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "UpdateStudent"
  ): TypedContractMethod<
    [_new_name: string, _new_age: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "ViewStudent"
  ): TypedContractMethod<
    [],
    [
      [string, bigint, string, bigint, bigint] & {
        name: string;
        age: bigint;
        email: string;
        gender: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "ViewStudents"
  ): TypedContractMethod<
    [],
    [SchoolManagementSystem.StudentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "studentAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "students"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, string, bigint, bigint, string] & {
        name: string;
        age: bigint;
        email: string;
        gender: bigint;
        status: bigint;
        school_name: string;
      }
    ],
    "view"
  >;

  filters: {};
}
