[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable the IR-based code generator to handle stack too deep errors
via_ir = true

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Other compiler settings
solc_version = "0.8.30"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
