[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

# Mainnet fork configuration
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# Test configuration
[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = true

# Fork test configuration
[profile.fork]
src = "contracts"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"

# Remappings for imports
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]