/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gameitemSol from "./Gameitem.sol";
export type { gameitemSol };
import type * as gametokenSol from "./Gametoken.sol";
export type { gametokenSol };
export type { GameNFT } from "./GameNFT";
export type { LootBox } from "./LootBox";
