/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as messages from "./messages";
export type { messages };
export type { PiggyBank } from "./PiggyBank";
export type { PiggyBankFactory } from "./PiggyBankFactory";
