/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPiggyBankFactory,
  IPiggyBankFactoryInterface,
} from "../../../contracts/PiggyBank.sol/IPiggyBankFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "emitPenaltyReceived",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "emitTokenPenaltyReceived",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPiggyBankFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IPiggyBankFactoryInterface {
    return new Interface(_abi) as IPiggyBankFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPiggyBankFactory {
    return new Contract(address, _abi, runner) as unknown as IPiggyBankFactory;
  }
}
