[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
[dependencies]
OpenZeppelin = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts.git"}
permit2 = { git = "https://github.com/Uniswap/permit2.git" }
solmate = { git = "https://github.com/transmissions11/solmate.git" }
remappings = [
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "permit2/=lib/permit2/src/",
    "forge-std/=lib/forge-std/src/",
    "interfaces/=src/interfaces/",
    "mocks/=src/mocks/",
    "contracts/=src/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
