/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface FactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createNewMultisig"
      | "getAllMultisigs"
      | "getMultisigCount"
      | "listOfMultisigContracts"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createNewMultisig",
    values: [AddressLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllMultisigs",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMultisigCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "listOfMultisigContracts",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createNewMultisig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllMultisigs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMultisigCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "listOfMultisigContracts",
    data: BytesLike
  ): Result;
}

export interface Factory extends BaseContract {
  connect(runner?: ContractRunner | null): Factory;
  waitForDeployment(): Promise<this>;

  interface: FactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createNewMultisig: TypedContractMethod<
    [owners: AddressLike[], requiredSignatures: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAllMultisigs: TypedContractMethod<[], [string[]], "view">;

  getMultisigCount: TypedContractMethod<[], [bigint], "view">;

  listOfMultisigContracts: TypedContractMethod<
    [arg0: BigNumberish],
    [string],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createNewMultisig"
  ): TypedContractMethod<
    [owners: AddressLike[], requiredSignatures: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllMultisigs"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getMultisigCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "listOfMultisigContracts"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  filters: {};
}
