/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StudentManagement } from "./StudentManagement";
export * as factories from "./factories";
export { StudentManagement__factory } from "./factories/StudentManagement__factory";
