/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lootSol from './Loot.sol/index.js';
export type { lootSol };
export type { Counter } from './Counter.js';
export * as factories from './factories/index.js';
export { Counter__factory } from './factories/Counter__factory.js';
export type { LootBox } from './Loot.sol/LootBox.js';
export { LootBox__factory } from './factories/Loot.sol/LootBox__factory.js';