[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"

# Remappings for dependencies
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v3-core/=lib/v3-core/",
    "forge-std/=lib/forge-std/src/"
]

# RPC endpoints
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

sepolia = "${SEPOLIA_RPC_URL}"

# Etherscan API keys for contract verification
[etherscan]

sepolia = { key = "${ETHERSCAN_API_KEY}" }



# Test configuration
[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 256
depth = 15