/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from "./contracts";
export type { contracts };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as library from "./library";
export type { library };
export * as factories from "./factories";
export type { Child } from "./contracts/Child";
export { Child__factory } from "./factories/contracts/Child__factory";
export type { ERC20Token } from "./contracts/ERC20Token";
export { ERC20Token__factory } from "./factories/contracts/ERC20Token__factory";
export type { IERC20Token } from "./interfaces/IERC20Token";
export { IERC20Token__factory } from "./factories/interfaces/IERC20Token__factory";
export type { Errors } from "./library/Errors";
export { Errors__factory } from "./factories/library/Errors__factory";
