/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gameitemSol from "./Gameitem.sol";
export * as gametokenSol from "./Gametoken.sol";
export { GameNFT__factory } from "./GameNFT__factory";
export { LootBox__factory } from "./LootBox__factory";
