/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EmployeeManagement__factory } from "./EmployeeManagement__factory";
export { ISalaryDisburser__factory } from "./ISalaryDisburser__factory";
