/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as smsSol from "./Sms.sol";
export type { smsSol };
import type * as todoSol from "./Todo.sol";
export type { todoSol };
export * as factories from "./factories";
export type { SchoolManagementSystem } from "./Sms.sol/SchoolManagementSystem";
export { SchoolManagementSystem__factory } from "./factories/Sms.sol/SchoolManagementSystem__factory";
export type { TodoList } from "./Todo.sol/TodoList";
export { TodoList__factory } from "./factories/Todo.sol/TodoList__factory";
