/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EmployeeManagement } from "./EmployeeManagement";
export type { ISalaryDisburser } from "./ISalaryDisburser";
export * as factories from "./factories";
export { EmployeeManagement__factory } from "./factories/EmployeeManagement__factory";
export { ISalaryDisburser__factory } from "./factories/ISalaryDisburser__factory";
