/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SchMSys } from "./SchMSys";
export type { SchoolManagementSystem } from "./SchoolManagementSystem";
export * as factories from "./factories";
export { SchMSys__factory } from "./factories/SchMSys__factory";
export { SchoolManagementSystem__factory } from "./factories/SchoolManagementSystem__factory";
