/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace SchoolManagementSystem {
  export type StudentStruct = {
    name: string;
    age: BigNumberish;
    status: BigNumberish;
    exists: boolean;
  };

  export type StudentStructOutput = [
    name: string,
    age: bigint,
    status: bigint,
    exists: boolean
  ] & { name: string; age: bigint; status: bigint; exists: boolean };
}

export interface SchoolManagementSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "changeStatus"
      | "deleteStudent"
      | "getAllStudents"
      | "getStudent"
      | "getTotalStudents"
      | "registerStudent"
      | "students"
      | "updateStudent"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "changeStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteStudent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllStudents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getStudent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStudents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerStudent",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "students",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStudent",
    values: [BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "changeStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStudent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStudents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerStudent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "students", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateStudent",
    data: BytesLike
  ): Result;
}

export interface SchoolManagementSystem extends BaseContract {
  connect(runner?: ContractRunner | null): SchoolManagementSystem;
  waitForDeployment(): Promise<this>;

  interface: SchoolManagementSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  changeStatus: TypedContractMethod<
    [_id: BigNumberish, _status: BigNumberish],
    [void],
    "nonpayable"
  >;

  deleteStudent: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  getAllStudents: TypedContractMethod<
    [],
    [SchoolManagementSystem.StudentStructOutput[]],
    "view"
  >;

  getStudent: TypedContractMethod<
    [_id: BigNumberish],
    [SchoolManagementSystem.StudentStructOutput],
    "view"
  >;

  getTotalStudents: TypedContractMethod<[], [bigint], "view">;

  registerStudent: TypedContractMethod<
    [_name: string, _age: BigNumberish],
    [void],
    "nonpayable"
  >;

  students: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        name: string;
        age: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  updateStudent: TypedContractMethod<
    [_id: BigNumberish, _name: string, _age: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "changeStatus"
  ): TypedContractMethod<
    [_id: BigNumberish, _status: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deleteStudent"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllStudents"
  ): TypedContractMethod<
    [],
    [SchoolManagementSystem.StudentStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStudent"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [SchoolManagementSystem.StudentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalStudents"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registerStudent"
  ): TypedContractMethod<
    [_name: string, _age: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "students"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        name: string;
        age: bigint;
        status: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "updateStudent"
  ): TypedContractMethod<
    [_id: BigNumberish, _name: string, _age: BigNumberish],
    [void],
    "nonpayable"
  >;

  filters: {};
}
