/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iUniswapSol from "./IUniswap.sol";
export type { iUniswapSol };
export type { IERC20 } from "./IERC20";
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { IERC20__factory } from "./factories/IERC20__factory";
export type { IUniSwap } from "./IUniswap.sol/IUniSwap";
export { IUniSwap__factory } from "./factories/IUniswap.sol/IUniSwap__factory";
export { Lock__factory } from "./factories/Lock__factory";
