/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StudentManagementFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createStudentMangementContract"
      | "getAllStudentManagementAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createStudentMangementContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllStudentManagementAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createStudentMangementContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllStudentManagementAddress",
    data: BytesLike
  ): Result;
}

export interface StudentManagementFactory extends BaseContract {
  connect(runner?: ContractRunner | null): StudentManagementFactory;
  waitForDeployment(): Promise<this>;

  interface: StudentManagementFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createStudentMangementContract: TypedContractMethod<[], [void], "nonpayable">;

  getAllStudentManagementAddress: TypedContractMethod<[], [string[]], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createStudentMangementContract"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllStudentManagementAddress"
  ): TypedContractMethod<[], [string[]], "view">;

  filters: {};
}
