/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multisigSol from "./multisig.sol";
export type { multisigSol };
import type * as multisigfactorySol from "./multisigfactory.sol";
export type { multisigfactorySol };
export type { Lock } from "./Lock";
export * as factories from "./factories";
export { Lock__factory } from "./factories/Lock__factory";
export type { Errors } from "./multisig.sol/Errors";
export { Errors__factory } from "./factories/multisig.sol/Errors__factory";
export type { Multisig } from "./multisig.sol/Multisig";
export { Multisig__factory } from "./factories/multisig.sol/Multisig__factory";
export type { MultisigFactory } from "./multisigfactory.sol/MultisigFactory";
export { MultisigFactory__factory } from "./factories/multisigfactory.sol/MultisigFactory__factory";
