[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Enable the optimizer and set the number of runs
optimizer = true
optimizer_runs = 200

# Enable the IR code generator to help with stack too deep errors
via_ir = true

# Set the solc version
solc_version = "0.8.20"

# Add remappings for imports
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]
