/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as multiSigSol from "./MultiSig.sol";
export { FactoryMultiSig__factory } from "./FactoryMultiSig__factory";
