/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace StudentManagementSystem {
  export type StudentStruct = {
    name: string;
    id: BigNumberish;
    age: BigNumberish;
    gender: BigNumberish;
    status: BigNumberish;
  };

  export type StudentStructOutput = [
    name: string,
    id: bigint,
    age: bigint,
    gender: bigint,
    status: bigint
  ] & { name: string; id: bigint; age: bigint; gender: bigint; status: bigint };
}

export interface StudentManagementSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "delete_student_details"
      | "id"
      | "nextId"
      | "register_student"
      | "students"
      | "update_student_data"
      | "view_all_students"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "delete_student_details",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "id", values?: undefined): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "register_student",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "students",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "update_student_data",
    values: [string, BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "view_all_students",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "delete_student_details",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "id", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "register_student",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "students", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "update_student_data",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "view_all_students",
    data: BytesLike
  ): Result;
}

export interface StudentManagementSystem extends BaseContract {
  connect(runner?: ContractRunner | null): StudentManagementSystem;
  waitForDeployment(): Promise<this>;

  interface: StudentManagementSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  delete_student_details: TypedContractMethod<
    [_index: BigNumberish],
    [void],
    "nonpayable"
  >;

  id: TypedContractMethod<[], [bigint], "view">;

  nextId: TypedContractMethod<[], [bigint], "view">;

  register_student: TypedContractMethod<
    [
      _name: string,
      _id: BigNumberish,
      _age: BigNumberish,
      _gender: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  students: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        name: string;
        id: bigint;
        age: bigint;
        gender: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  update_student_data: TypedContractMethod<
    [
      _new_name: string,
      _new_age: BigNumberish,
      _new_gender: BigNumberish,
      _new_status: BigNumberish,
      _index: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  view_all_students: TypedContractMethod<
    [],
    [StudentManagementSystem.StudentStructOutput[]],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "delete_student_details"
  ): TypedContractMethod<[_index: BigNumberish], [void], "nonpayable">;
  getFunction(nameOrSignature: "id"): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "register_student"
  ): TypedContractMethod<
    [
      _name: string,
      _id: BigNumberish,
      _age: BigNumberish,
      _gender: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "students"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, bigint] & {
        name: string;
        id: bigint;
        age: bigint;
        gender: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "update_student_data"
  ): TypedContractMethod<
    [
      _new_name: string,
      _new_age: BigNumberish,
      _new_gender: BigNumberish,
      _new_status: BigNumberish,
      _index: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "view_all_students"
  ): TypedContractMethod<
    [],
    [StudentManagementSystem.StudentStructOutput[]],
    "view"
  >;

  filters: {};
}
