/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as daoSol from "./DAO.sol";
export type { daoSol };
import type * as daonftSol from "./DAONFT.sol";
export type { daonftSol };
import type * as eip7432Sol from "./EIP7432.sol";
export type { eip7432Sol };
import type * as interfaces from "./interfaces";
export type { interfaces };
