/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IAllowanceTransfer {
  export type PermitDetailsStruct = {
    token: AddressLike;
    amount: BigNumberish;
    expiration: BigNumberish;
    nonce: BigNumberish;
  };

  export type PermitDetailsStructOutput = [
    token: string,
    amount: bigint,
    expiration: bigint,
    nonce: bigint
  ] & { token: string; amount: bigint; expiration: bigint; nonce: bigint };

  export type PermitSingleStruct = {
    details: IAllowanceTransfer.PermitDetailsStruct;
    spender: AddressLike;
    sigDeadline: BigNumberish;
  };

  export type PermitSingleStructOutput = [
    details: IAllowanceTransfer.PermitDetailsStructOutput,
    spender: string,
    sigDeadline: bigint
  ] & {
    details: IAllowanceTransfer.PermitDetailsStructOutput;
    spender: string;
    sigDeadline: bigint;
  };
}

export interface PermitSwapInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PERMIT2"
      | "Router"
      | "permitAndSwap"
      | "tokenBalancesByUser"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "PERMIT2", values?: undefined): string;
  encodeFunctionData(functionFragment: "Router", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "permitAndSwap",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      IAllowanceTransfer.PermitSingleStruct,
      BigNumberish,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenBalancesByUser",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "PERMIT2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "Router", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "permitAndSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenBalancesByUser",
    data: BytesLike
  ): Result;
}

export interface PermitSwap extends BaseContract {
  connect(runner?: ContractRunner | null): PermitSwap;
  waitForDeployment(): Promise<this>;

  interface: PermitSwapInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PERMIT2: TypedContractMethod<[], [string], "view">;

  Router: TypedContractMethod<[], [string], "view">;

  permitAndSwap: TypedContractMethod<
    [
      token: AddressLike,
      out: AddressLike,
      amount: BigNumberish,
      nonce: BigNumberish,
      deadline: BigNumberish,
      permitSingle: IAllowanceTransfer.PermitSingleStruct,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  tokenBalancesByUser: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PERMIT2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "Router"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "permitAndSwap"
  ): TypedContractMethod<
    [
      token: AddressLike,
      out: AddressLike,
      amount: BigNumberish,
      nonce: BigNumberish,
      deadline: BigNumberish,
      permitSingle: IAllowanceTransfer.PermitSingleStruct,
      v: BigNumberish,
      r: BytesLike,
      s: BytesLike,
      signature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenBalancesByUser"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  filters: {};
}
