[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.17"

# Enable optimizer and via-ir to help with stack too deep errors
optimizer = true
optimizer_runs = 1000
via_ir = true

# Gas reports
gas_reports = ["*"]

# Enable FFI for scripts
ffi = true

# Test configuration
[profile.default.model_checker]
contracts = {}
engine = "none"
timeout = 10000

# CI profile with more strict settings
[profile.ci]
optimizer_runs = 10000
via_ir = true

# Local development profile
[profile.local]
optimizer = false
via_ir = false

# Remappings for dependencies
remappings = [
    "forge-std/=lib/forge-std/src/",
]

# RPC endpoints (add your own)
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
local = "http://localhost:8545"

# Etherscan configuration
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }