[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
cache_path = "cache"

solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
via_ir = false

remappings = [
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
mainnet = "https://eth-mainnet.alchemyapi.io/v2/${API_KEY_ALCHEMY}"
goerli = "https://eth-goerli.alchemyapi.io/v2/${API_KEY_ALCHEMY}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }