/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./Interfaces";
export type { interfaces };
import type * as contracts from "./contracts";
export type { contracts };
export * as factories from "./factories";
export type { ERC20Token } from "./contracts/ERC20Token";
export { ERC20Token__factory } from "./factories/contracts/ERC20Token__factory";
export type { Factory } from "./contracts/Factory";
export { Factory__factory } from "./factories/contracts/Factory__factory";
export type { IERC20Token } from "./Interfaces/IERC20Tken.sol/IERC20Token";
export { IERC20Token__factory } from "./factories/Interfaces/IERC20Tken.sol/IERC20Token__factory";
