[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200


# Enable FFI for Chainlink integration
ffi = true

# Test configuration
[fuzz]
runs = 500

remappings = [
  "@chainlink/contracts=lib/chainlink/contracts"
]

[rpc_endpoints]
sepolia = "${RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
