[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "paris"
solc_version = "0.8.28"
auto_detect_solc = false

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@uniswap/v3-periphery=lib/v3-periphery",
    "permit2=lib/permit2",
    "@uniswap/v3-core=lib/v3-core"
]

[rpc_endpoints]
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"

[etherscan]
lisk-sepolia = { chain = 4202, key = "123", url = "https://sepolia-blockscout.lisk.com/api" }

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15