/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ISalaryDisburser__factory } from "./ISalaryDisburser__factory";
export { SchoolManagement__factory } from "./SchoolManagement__factory";
export { SchoolManagementSystem__factory } from "./SchoolManagementSystem__factory";
