/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as erc20Sol from "./ERC20.sol";
export { ERC20Factory__factory } from "./ERC20Factory__factory";
export { IERC20__factory } from "./IERC20__factory";
