/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC20Factory__factory } from "./ERC20Factory__factory";
export { ERC20Standard__factory } from "./ERC20Standard__factory";
