/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IPiggyBank__factory } from "./IPiggyBank__factory";
export { IPiggyBankFactory__factory } from "./IPiggyBankFactory__factory";
