/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Web3BridgeAccess } from "./Web3BridgeAccess";
export * as factories from "./factories";
export { Web3BridgeAccess__factory } from "./factories/Web3BridgeAccess__factory";
